name: Build-Web

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('./Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Get pnpm store path
        id: pnpm-store
        shell: pwsh
        run: |
          $STORE_PATH = pnpm store path --silent
          "STORE_PATH=$STORE_PATH" >> $env:GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install wasm-pack
        run: cargo install wasm-pack || true

      - name: Build Web app
        working-directory: crabeam-viewer/crabeam-site
        run: |
          pnpm install
          pnpm build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: crabeam-viewer/crabeam-site/dist
